const roleList = ['Software Engineer', 'Frontend Developer', 'Backend Developer', 'Full Stack Developer', 'Mobile Developer', 'Database Administrator', 'Data Scientist', 'Data Analyst', 'Data Engineer', 'Cloud Architect', 'Cloud Engineer', 'DevOps Engineer', 'Machine Learning Engineer', 'Artificial Intelligence Engineer', 'Computer Vision Engineer', 'Natural Language Processing Engineer', 'Robotics Engineer', 'Internet of Things (IoT) Developer', 'Virtual Reality (VR) Developer', 'Augmented Reality (AR) Developer', 'Blockchain Developer', 'Cybersecurity Analyst', 'Network Administrator', 'System Administrator', 'Technical Writer', 'User Experience (UX) Designer', 'User Interface (UI) Designer', 'Graphic Designer', 'Game Developer', 'Computer Programmer', 'Software Tester', 'Quality Assurance Engineer', 'Agile Project Manager', 'Product Manager', 'Technical Project Manager', 'Big Data Engineer', 'Hadoop Administrator', 'Spark Developer', 'NoSQL Database Administrator', 'Python Developer', 'Java Developer', 'JavaScript Developer', 'C++ Developer', 'C# Developer', 'Ruby Developer', 'PHP Developer', 'SQL Developer', 'Swift Developer', 'Objective-C Developer', 'Kotlin Developer', 'R Developer', 'MATLAB Developer', 'Scala Developer', 'Go Developer', 'Perl Developer'];
const recruiterBios = [
  "Hi, I'm Ashley. With a keen eye for talent, I help companies find the right fit for their team. Let's chat about your career goals!",
  "Hello, my name is Tom. I'm a recruiter with a passion for helping individuals find their dream job. Let's work together to make it happen!",
  "Hey there, I'm Emma. As a recruiter, I value transparency and communication. Let's connect and discuss your next career move.",
  "Hi, I'm Ryan. I believe in building strong relationships with both clients and candidates. Let me know how I can help you achieve your career aspirations.",
  "Greetings, I'm Rachel. With a background in HR and recruitment, I have the skills to help you succeed in your job search. Let's get started!",
  "Hi, I'm Mark. With years of experience in recruitment, I have the expertise to guide you through the job search process. Let's work together!",
  "Hello, my name is Grace. I specialize in placing candidates in the healthcare industry. Let's talk about your career aspirations and how I can assist you.",
  "Hey, I'm Jake. As a recruiter, I'm committed to helping candidates find their perfect fit. Let's connect and make it happen!",
  "Hi, I'm Laura. I have a knack for identifying talent and matching it with the right company culture. Let's discuss your next career move.",
  "Hi, I'm Chris. As a recruiter, I strive to create a positive and supportive experience for all candidates. Let's work together to find your dream job.",
  "Hello, I'm Stephanie. I'm dedicated to providing a personalized approach to recruitment. Let's connect and see how I can help you.",
  "Hey there, I'm David. I have a passion for connecting candidates with meaningful career opportunities. Let's discuss how I can assist you in your job search.",
  "Hi, I'm Samantha. With a focus on building lasting relationships, I'm here to help you find your next career move. Let's connect!",
  "Hello, my name is Alex. I specialize in placing candidates in the finance industry. Let's work together to find your next opportunity.",
  "Hey, I'm Sarah. As a recruiter, I believe in providing a seamless experience for all candidates. Let's talk about your career goals.",
  "Hi, I'm Eric. With a data-driven approach to recruitment, I'm committed to finding the best fit for both the candidate and the company. Let's chat!",
  "Hi, I'm Emily. As a recruiter, I understand that the job search process can be overwhelming. Let me help guide you through it.",
  "Hello, I'm Tyler. With a passion for connecting candidates with innovative companies, let's explore the possibilities together.",
  "Hey there, I'm Jessica. I have experience in a variety of industries and I'm here to help you achieve your career aspirations. Let's connect!",
  "Hi, I'm Jason. With a focus on finding the right fit for both the candidate and the company, let's work together to achieve your career goals.",
  "Hello, my name is Lauren. I specialize in placing candidates in the marketing and advertising industry. Let's connect and discuss your next move.",
  "Hey, I'm Matthew. As a recruiter, I believe in being a partner in your career journey. Let's work together to find your dream job.",
  "Hi, I'm Kelly. With a background in human resources, I have the expertise to help you succeed in your job search. Let's get started!",
  "Hi, I'm Daniel. As a recruiter, I strive to provide a positive and supportive experience for all candidates. Let's connect and discuss your career aspirations.",
  "Hello, I'm Megan. With a focus on building strong relationships, let me assist you in finding your next career move.",
  "Hey there, I'm Brandon. I have experience placing candidates in a variety of industries, and I'm here to help you navigate the job market. Let's chat!",
];
const atsList = [
  'Jobvite',
  'Workday',
  'Taleo',
  'Greenhouse',
  'Lever',
  'iCIMS',
  'SmartRecruiters',
  'Breezy HR',
  'Recruiterbox',
  'ApplicantPro',
  'JazzHR',
  'Workable',
  'JobAdder',
  'Bullhorn',
  'Newton',
  'JobScore',
  'Zoho Recruit',
  'CATS',
  'Recruitee',
  'Jobscience',
  'Lumesse',
  'PeopleFluent',
  'Kenexa BrassRing',
  'Jobscience',
  'Jobvite',
  'SmartRecruiters',
  'Breezy HR',
  'Lever',
  'Greenhouse',
  'iCIMS',
];
const fundList = [
  'Vanguard Total Bond Market Index Fund',
  'Fidelity Total Bond Fund',
  'iShares Core U.S. Aggregate Bond ETF',
  'Vanguard Short-Term Treasury Fund',
  'Fidelity Money Market Fund',
  'Vanguard High Dividend Yield Index Fund',
  'SPDR Gold Shares',
  'Vanguard Real Estate Index Fund',
  'Vanguard Intermediate-Term Bond Index Fund',
  'Fidelity Low-Priced Stock Fund',
  'Fidelity Blue Chip Growth Fund',
  'T. Rowe Price Equity Income Fund',
  'Vanguard Dividend Growth Fund',
  'Vanguard Total International Stock Index Fund',
  'Fidelity International Index Fund',
  'iShares MSCI EAFE ETF',
  'Vanguard Emerging Markets Stock Index Fund',
  'Fidelity Emerging Markets Fund',
  'American Funds Capital World Growth and Income Fund',
  'Vanguard Target Retirement 2055 Fund',
  'Vanguard Target Retirement 2060 Fund',
  'Fidelity Balanced Fund',
  'T. Rowe Price Retirement 2050 Fund',
  'Vanguard LifeStrategy Moderate Growth Fund',
  'American Funds Balanced Fund',
  'Vanguard Wellington Fund',
  'Fidelity Four-in-One Index Fund',
  'Vanguard STAR Fund',
  'T. Rowe Price Capital Appreciation Fund',
  'Fidelity Puritan Fund',
  'Vanguard Total World Stock Index Fund',
  'Fidelity ZERO Total Market Index Fund',
  'SPDR Portfolio S&P 500 ETF',
  'iShares Russell 2000 ETF',
  'Vanguard Real Estate ETF',
  'Invesco QQQ Trust',
  'Vanguard Short-Term Bond Index Fund',
  'iShares National Muni Bond ETF',
  'Vanguard Information Technology Index Fund',
  'Fidelity Growth Company Fund',
];
const jobTypes = ['Full Time', 'Part Time', 'Work From Home', 'Internship', 'Trainee'];
const skills = ['Web development', 'Mobile app development', 'Database management', 'Data analysis', 'Data visualization', 'Data mining', 'Cloud computing', 'Artificial intelligence', 'Machine learning', 'Deep learning', 'Natural language processing', 'Computer vision', 'Robotics', 'Internet of Things (IoT)', 'Virtual reality (VR)', 'Augmented reality (AR)', 'Blockchain', 'Cybersecurity', 'Network administration', 'Server administration', 'Software testing', 'Quality assurance', 'Technical writing', 'User experience (UX) design', 'User interface (UI) design', 'Graphic design', 'Game development', 'Computer programming', 'Object-oriented programming', 'Functional programming', 'Scripting languages', 'Version control', 'DevOps', 'Agile development', 'Project management', 'Big data', 'Hadoop', 'Spark', 'NoSQL databases', 'Python', 'Java', 'JavaScript', 'C++', 'C#', 'Ruby', 'PHP', 'SQL', 'Swift', 'Objective-C', 'Kotlin', 'R', 'MATLAB', 'Scala', 'Go', 'Perl', 'Assembly language'];
const cityList = ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Ahmedabad', 'Kolkata', 'Surat', 'Pune', 'Jaipur', 'Lucknow', 'Kanpur', 'Nagpur', 'Visakhapatnam', 'Bhopal', 'Patna', 'Ludhiana', 'Agra', 'Nashik', 'Vadodara', 'Faridabad', 'Madurai', 'Varanasi', 'Jamshedpur', 'Srinagar', 'Allahabad', 'Ranchi', 'Thiruvananthapuram', 'Amritsar', 'Guwahati', 'Coimbatore', 'Gwalior', 'Vijayawada', 'Jodhpur', 'Raipur', 'Kota', 'Bareilly', 'Mangalore', 'Tiruchirappalli', 'Hubli-Dharwad', 'Aligarh', 'Salem', 'Moradabad', 'Bhubaneswar', 'Gurgaon', 'Alwar', 'Guntur', 'Bhiwandi', 'Nellore', 'Amravati', 'Nanded', 'Gulbarga', 'Dehradun', 'New Delhi', 'Bilaspur', 'Shimla', 'Jammu', 'Kurnool', 'Chandigarh', 'Tiruppur', 'Kozhikode', 'Thrissur', 'Barasat', 'Arrah', 'Karimnagar', 'Malegaon', 'Muzaffarnagar', 'Bhatpara', 'Raichur', 'Jalpaiguri', 'Bally', 'Bongaigaon', 'Kharagpur', 'Saharsa', 'Suryapet', 'Jhansi', 'Ulhasnagar', 'Madhyamgram', 'Shivamogga', 'Madanapalle', 'Jorhat', 'Habra', 'Palwal', 'Chinsurah', 'Bagaha', 'Baharampur', 'Haldwani'];
const titleList = ['Software Engineer', 'Frontend Developer', 'Backend Developer', 'Full Stack Developer', 'Mobile Developer', 'Database Administrator', 'Data Scientist', 'Data Analyst', 'Data Engineer', 'Cloud Architect', 'Cloud Engineer', 'DevOps Engineer', 'Machine Learning Engineer', 'Artificial Intelligence Engineer', 'Computer Vision Engineer', 'Natural Language Processing Engineer', 'Robotics Engineer', 'Internet of Things (IoT) Developer', 'Virtual Reality (VR) Developer', 'Augmented Reality (AR) Developer', 'Blockchain Developer', 'Cybersecurity Analyst', 'Network Administrator', 'System Administrator', 'Technical Writer', 'User Experience (UX) Designer', 'User Interface (UI) Designer', 'Graphic Designer', 'Game Developer', 'Computer Programmer', 'Software Tester', 'Quality Assurance Engineer', 'Agile Project Manager', 'Product Manager', 'Technical Project Manager', 'Big Data Engineer', 'Hadoop Administrator', 'Spark Developer', 'NoSQL Database Administrator', 'Python Developer', 'Java Developer', 'JavaScript Developer', 'C++ Developer', 'C# Developer', 'Ruby Developer', 'PHP Developer', 'SQL Developer', 'Swift Developer', 'Objective-C Developer', 'Kotlin Developer', 'R Developer', 'MATLAB Developer', 'Scala Developer', 'Go Developer', 'Perl Developer'];
const collegeList = [
  'Indian Institute of Technology Bombay',
  'Indian Institute of Technology Delhi',
  'Indian Institute of Technology Madras',
  'Indian Institute of Technology Kharagpur',
  'Indian Institute of Technology Kanpur',
  'Indian Institute of Technology Roorkee',
  'Indian Institute of Technology Guwahati',
  'Indian Institute of Technology Hyderabad',
  'Indian Institute of Technology Ropar',
  'Indian Institute of Technology Bhubaneswar',
  'Indian Institute of Technology Gandhinagar',
  'Indian Institute of Technology Patna',
  'Indian Institute of Technology Mandi',
  'Indian Institute of Technology Indore',
  'Indian Institute of Technology Jodhpur',
  'Indian Institute of Technology Tirupati',
  'Indian Institute of Technology Palakkad',
  'Indian Institute of Technology Bhilai',
  'Indian Institute of Technology Goa',
  'Indian Institute of Technology Jammu',
  'Indian Institute of Technology Dharwad',
  'Indian Institute of Science Bangalore',
  'Jawaharlal Nehru University',
  'University of Delhi',
  'Banaras Hindu University',
  'University of Mumbai',
  'University of Calcutta',
  'University of Madras',
  'University of Pune',
  'University of Hyderabad',
  'University of Allahabad',
  'University of Lucknow',
  'Aligarh Muslim University',
  'Jamia Millia Islamia',
  'Tata Institute of Social Sciences',
  'Indian Statistical Institute Kolkata',
  'National Law School of India University Bangalore',
  'National Institute of Technology Tiruchirappalli',
  'National Institute of Technology Warangal',
  'National Institute of Technology Surathkal',
  'Birla Institute of Technology and Science Pilani',
  'Indian Institute of Management Ahmedabad',
  'Indian Institute of Management Bangalore',
  'Indian Institute of Management Calcutta',
  'Indian Institute of Management Lucknow',
  'Indian Institute of Management Kozhikode',
  'Indian Institute of Management Indore',
  'Indian Institute of Management Shillong',
  'Indian Institute of Management Rohtak',
  'Indian Institute of Management Ranchi',
  'Indian Institute of Management Raipur',
  'Indian Institute of Management Udaipur',
  'Indian Institute of Management Trichy',
  'Indian Institute of Management Nagpur',
  'Indian Institute of Management Visakhapatnam',
  'Indian Institute of Management Bodh Gaya',
  'Indian Institute of Management Amritsar',
  'Indian Institute of Management Sirmaur',
  'Indian Institute of Management Jammu',
  'Indian Institute of Management Sambalpur',
  'Indian Institute of Management Kashipur',
  'Indian Institute of Technology Delhi',
  'Indian Institute of Technology Kharagpur',
  'Indian Institute of Technology Bombay',
  'Indian Institute of Technology Kanpur',
  'Indian Institute of Technology Madras',
  'Indian Institute of Technology Roorkee',
  'Indian Institute of Technology Guwahati',
  'Delhi Technological University',
  'Netaji Subhas University of Technology',
  'Birla Institute of Technology, Mesra',
  'Thapar Institute of Engineering and Technology',
  'Vellore Institute of Technology',
  'Indian Institute of Information Technology, Allahabad',
  'Indian Institute of Information Technology, Hyderabad',
  'International Institute of Information Technology, Bangalore',
  'International Institute of Information Technology, Hyderabad',
  'Indian Institute of Science Education and Research, Pune',
  'Indian Institute of Science Education and Research, Kolkata',
  'Indian Institute of Science Education and Research, Mohali',
  'Indian Institute of Science Education and Research, Bhopal',
  'Indian Institute of Science Education and Research, Tirupati',
  'Indian Institute of Science Education and Research, Thiruvananthapuram',
  'Indian Institute of Technology Mandi Kamand',
  'Indian Institute of Technology Bhilai',
  'Indian Institute of Technology Jammu',
];

export { roleList,
  recruiterBios,
  atsList, fundList,
  jobTypes,
  skills,
  cityList,
  titleList,
  collegeList };
